services:
  display-mbsport:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    environment:
      - VITE_API_URL=${VITE_API_URL:-https://api.mbracesrd.lat}
    restart: unless-stopped
